const BODY={str:17,dex:13,con:15};
const HEADS={
 o:{name:'OINKER',cls:'Barbarian',side:'Right head, right arm',int:8,wis:10,cha:14,die:12,worn:['Greatsword','Battleaxe','Hay wig','Purple scale helmet','Harness','Loincloth']},
 b:{name:'BOINKER',cls:'Fighter',side:'Left head, left arm',int:12,wis:12,cha:10,die:10,worn:['Brick mace','Flail','Black oily helmet','Harness','Loincloth']}
};
const CHECKS=[['Strength','Athletics',1,'Barbarian'],['Dexterity','Acrobatics',0,''],['Dexterity','Sleight of Hand',0,''],['Dexterity','Stealth',0,''],['Intelligence','Arcana',0,''],['Intelligence','History',0,''],['Intelligence','Investigation',0,''],['Intelligence','Nature',0,''],['Intelligence','Religion',1,'Hermit'],['Wisdom','Animal Handling',1,'Fighter'],['Wisdom','Insight',0,''],['Wisdom','Medicine',1,'Hermit'],['Wisdom','Perception',1,'Fighter'],['Wisdom','Survival',1,'Barbarian'],['Charisma','Deception',0,''],['Charisma','Intimidation',0,''],['Charisma','Performance',0,''],['Charisma','Persuasion',0,'']];
const BARB=[['Berserker','L3 Frenzy extra attack in rage, then exhaustion. No element. Permanent.'],['TotemWarrior','L3 pick Bear Eagle or Wolf with the DM. Bear resists almost all damage in rage. Permanent.'],['Battlerager','L3 spiked armor. Weak without that armor. Permanent.'],['AncestralGuardian','L3 first hit in rage marks the target so allies take less. Permanent.'],['StormHerald','L3 pick Desert Sea or Tundra. Locks fire, storm, or cold. Permanent.'],['Zealot','L3 extra radiant or necrotic on a rage hit. Not a wizard. Permanent.'],['Beast','L3 rage grows bite, claws, or tail. Permanent.'],['WildMagic','L3 rage can roll random magic. Chaos. Permanent.'],['Giant','L3 grow and throw. Later giant type can lock an element. Permanent.']];
const FIGHT=[['Champion','L3 crit on 19-20. No spells. Permanent.'],['BattleMaster','L3 three maneuvers and superiority dice. Permanent.'],['EldritchKnight','L3 a few wizard spells. Soft lock to abjuration and evocation. Permanent.'],['Banneret','L3 Second Wind also heals nearby allies. Permanent.'],['ArcaneArcher','L3 magic arrows. Needs a bow. Permanent.'],['Cavalier','L3 mark and guard the space next to you. Permanent.'],['Samurai','L3 Fighting Spirit bursts of advantage. Permanent.'],['PsiWarrior','L3 mind-force dice. Not wizard slots. Permanent.'],['RuneKnight','L3 giant runes. Become Large. Some runes have an element. Permanent.'],['EchoKnight','L3 a copy of you. No element. Permanent.']];
const $=id=>document.getElementById(id);
const LOCK=document.documentElement.getAttribute('data-head')||'o';
let who=LOCK,goldN=40,bag=[],notes='',oLv=2,bLv=2,rage=2,raging=false,reckless=false,sw=1,surge=1;
let pool={o:{hp:23,max:23,temp:0},b:{hp:20,max:20,temp:0}};
let hands={right:'Greatsword',left:'Brick mace'},harness=['Battleaxe','Flail'],ground=[],path={o:'',b:''};
if(typeof picked==='undefined') window.picked={style:'',asi:{}};
function mod(s){return Math.floor((s-10)/2)}
function signed(n){return(n>=0?'+':'')+n}
function lv(){return who==='o'?oLv:bLv}
function pb(){const l=lv();return l>=17?6:l>=13?5:l>=9?4:l>=5?3:2}
function sc(ab){return ab==='Strength'?BODY.str:ab==='Dexterity'?BODY.dex:ab==='Constitution'?BODY.con:ab==='Intelligence'?HEADS[who].int:ab==='Wisdom'?HEADS[who].wis:HEADS[who].cha}
function say(t){if($('say'))$('say').textContent=t||''}
function hit(){return mod(BODY.str)+pb()}
function ac(){return 10+mod(BODY.dex)+mod(BODY.con)}
function store(){return 'ettin_'+LOCK}
function codeName(s){return String(s||'').replace(/\s+/g,'')}
function niceName(s){return String(s||'').replace(/([a-z])([A-Z])/g,'$1 $2')}
function writeHash(){var h='#o='+oLv+'-'+codeName(path.o)+'-'+pool.o.hp+'-'+pool.o.max+';b='+bLv+'-'+codeName(path.b)+'-'+pool.b.hp+'-'+pool.b.max+';g='+goldN;if(location.hash!==h)history.replaceState(null,'',h);}
function readHash(){var raw=(location.hash||'').replace(/^#/,'');if(!raw)return false;raw.split(';').forEach(function(part){var kv=part.split('=');if(kv.length<2)return;var k=kv[0],bits=kv[1].split('-');if(k==='g'&&bits[0])goldN=parseInt(bits[0],10)||goldN;if(k==='o'||k==='b'){if(bits[0]){var n=parseInt(bits[0],10);if(n>=1&&n<=20){if(k==='o')oLv=n;else bLv=n;}}if(bits[1])path[k]=niceName(bits[1]);if(bits[2])pool[k].hp=parseInt(bits[2],10)||pool[k].hp;if(bits[3])pool[k].max=parseInt(bits[3],10)||pool[k].max;}});return true;}
function save(){writeHash();try{localStorage.setItem(store(),JSON.stringify({pool,goldN,bag,notes:$('notes')?$('notes').value:'',oLv,bLv,rage,raging,reckless,sw,surge,hands,harness,ground,path,picked}))}catch(e){}}
function load(){try{var s=JSON.parse(localStorage.getItem(store())||localStorage.getItem('ettinV2')||'null');if(s){if(s.pool){if(s.pool.o)Object.assign(pool.o,s.pool.o);if(s.pool.b)Object.assign(pool.b,s.pool.b)}if(s.goldN!=null)goldN=s.goldN;if(s.bag)bag=s.bag;if(s.notes!=null)notes=s.notes;if(s.oLv)oLv=s.oLv;if(s.bLv)bLv=s.bLv;if(s.rage!=null)rage=s.rage;if(s.raging!=null)raging=s.raging;if(s.reckless!=null)reckless=s.reckless;if(s.sw!=null)sw=s.sw;if(s.surge!=null)surge=s.surge;if(s.hands)hands=s.hands;if(s.harness)harness=s.harness;if(s.ground)ground=s.ground;if(s.path)Object.assign(path,s.path);}}catch(e){}readHash();writeHash();}
function tab(id){['fight','scores','checks','pack','journal'].forEach(x=>{const p=$('p-'+x);if(p)p.className=x===id?'':'hide';['t-','b-'].forEach(pre=>{const b=$(pre+x);if(b)b.className=x===id?'on':''})})}
function explain(k){if(k==='ac')say('Armor Class '+ac()+'. 10 + Dexterity '+signed(mod(BODY.dex))+' + Constitution '+signed(mod(BODY.con))+'.');if(k==='init')say('Initiative '+signed(mod(BODY.dex))+'. Roll d20 + Dexterity.');if(k==='speed')say('Speed '+(who==='o'&&oLv>=5?40:30)+' feet.');if(k==='pp')say('Passive Perception '+(10+mod(HEADS[who].wis)+pb())+'.');if(k==='hd')say('Hit Dice '+lv()+'d'+HEADS[who].die+'.')}
function paintHUD(){const h=HEADS[who],p=pool[who];$('name').textContent=h.name;$('line').textContent=h.cls+' '+lv()+' \u00b7 Hermit \u00b7 '+h.side+(path[who]?' \u00b7 '+niceName(path[who]):'');$('lv').textContent=lv();$('hp').textContent=p.hp;$('hpMax').textContent=p.max;$('ac').textContent=ac();$('init').textContent=signed(mod(BODY.dex));$('pp').textContent=10+mod(h.wis)+pb();if($('temp'))$('temp').textContent=p.temp;if($('maxLab'))$('maxLab').textContent=p.max;if($('hdLine'))$('hdLine').textContent='Hit Dice '+lv()+'d'+h.die;if($('gp'))$('gp').textContent=goldN;if($('notes'))$('notes').value=notes}
function paintScores(){const blocks=[['STR',BODY.str,1],['DEX',BODY.dex,0],['CON',BODY.con,1],['INT',HEADS[who].int,0],['WIS',HEADS[who].wis,0],['CHA',HEADS[who].cha,0]];function box(a){const m=mod(a[1]),sav=m+(a[2]?pb():0);const el=document.createElement('div');el.className='ab';el.innerHTML='<div>'+a[0]+'</div><div class="mod">'+signed(m)+'</div><div class="sub">score '+a[1]+'</div><div class="sub">save '+signed(sav)+'</div>';el.onclick=()=>say(a[0]+' score '+a[1]+' modifier '+signed(m)+(a[2]?'. Save trained +'+pb():'. Save not trained')+'.');return el}['railAbs','phoneAbs'].forEach(id=>{const r=$(id);if(!r)return;r.innerHTML='';blocks.forEach(a=>r.appendChild(box(a)))})}
function dieFor(n){return n==='Greatsword'?'2d6':n==='Brick mace'?'1d12':'1d8'}
function hpBump(w){return(w==='o'?7:6)+mod(BODY.con)}
function applyLevel(w){const g=hpBump(w);pool[w].max+=g;pool[w].hp=Math.min(pool[w].max,pool[w].hp+g)}
function pickPath(kind){path[who]=kind;say(kind+' locked. Copy the address bar and send that full link.');save();paintAll();}
function nextBits(){var n=lv(),h='',cls=who==='o'?'Barbarian':'Fighter';function card(t,d){h+='<div class="card"><div><b>'+t+'</b><p class="muted">'+d+'</p></div></div>'}if(n>=4)card(cls+' 4','Ability Score Improvement: raise two scores by 1, or one by 2, or a feat.');if(who==='o'&&n>=5)card('Barbarian 5','Extra Attack. Walk 40 feet if not in heavy armor.');if(who==='b'&&n>=5)card('Fighter 5','Extra Attack: two attacks.');if(n>=6&&path[who])card(cls+' 6',niceName(path[who])+' next path feature.');if(n>=8)card(cls+' 8','Ability Score Improvement or feat.');if(who==='b'&&n>=9)card('Fighter 9','Indomitable: reroll one failed save per long rest.');if(n>=10&&path[who])card(cls+' 10',niceName(path[who])+' path feature.');if(who==='b'&&n>=11)card('Fighter 11','Extra Attack 2: three attacks.');if(n>=12)card(cls+' 12','Ability Score Improvement or feat.');if(n>=14&&path[who])card(cls+' 14',niceName(path[who])+' path feature.');if(n>=16)card(cls+' 16','Ability Score Improvement or feat.');if(who==='b'&&n>=17)card('Fighter 17','Action Surge twice. Indomitable twice.');if(n>=19)card(cls+' 19','Ability Score Improvement or feat.');if(who==='o'&&n>=20)card('Barbarian 20','Strength and Constitution +4. Rage unlimited.');if(who==='b'&&n>=20)card('Fighter 20','Extra Attack 3: four attacks.');return h;}
function levelPanel(){var n=lv();if(n<3)return '<div class="card"><div><b>Levels 1 to 20</b><p class="muted">Official last level is 20. Tap + to reach 3, then pick a path.</p></div></div>';var list=who==='o'?BARB:FIGHT;var h='';if(path[who]){h+='<div class="card"><div><b>Subclass: '+niceName(path[who])+'</b><p class="muted">Permanent. Send the full address-bar link so the other phone loads this pick.</p></div><button type="button" onclick="path[who]=\'\';save();paintAll()">Change</button></div>';h+=nextBits();return h;}h+='<div class="card"><div><b>Level 3 \u2014 pick a subclass</b><p class="muted">Tap Choose. Then copy the address bar and send that link.</p></div></div>';list.forEach(function(row){h+='<div class="card"><div><b>'+niceName(row[0])+'</b><p class="muted">'+row[1]+'</p></div><button type="button" onclick="pickPath(\''+row[0]+'\')">Choose '+niceName(row[0])+'</button></div>';});return h;}
function lvlChg(d){who=LOCK;const before=lv();if(who==='o')oLv=Math.max(1,Math.min(20,oLv+d));else bLv=Math.max(1,Math.min(20,bLv+d));const after=lv();if(after>before){applyLevel(who);var msg=HEADS[who].name+' is level '+after+'. HP +'+hpBump(who)+'. Max '+pool[who].max+'.';if(after>=3&&!path[who])msg+=' Pick a subclass below.';say(msg);}paintAll();save();}
function paintActs(){const root=$('acts');if(!root)return;const str=signed(mod(BODY.str)),tr=signed(pb()),tot=signed(hit()),held=who==='o'?hands.right:hands.left,adv=reckless&&who==='o';let h='';h+=levelPanel();h+='<h3>Action</h3><div class="card"><div><b>Attack with '+(held||'empty hand')+'</b><p class="muted">1. Roll a d20'+(adv?' twice, keep higher.':'')+'. 2. Add Strength '+str+' and training '+tr+' (now '+tot+'). 3. Tell the DM. 4. If it hits roll '+(held?dieFor(held):'1')+' + Strength '+str+(raging&&who==='o'?' + Rage +2.':'')+((who==='o'&&oLv>=5)||(who==='b'&&bLv>=5)?' Extra Attack: do this twice.':'')+'</p></div></div>';if(who==='o'){h+='<div class="card"><div><b>Rage</b><p class="muted">Bonus action. +2 melee damage.</p></div><span><button type="button" onclick="rage=Math.max(0,rage-1);paintActs();save()">-</button> <b>'+rage+'/'+(oLv>=20?6:oLv>=17?6:oLv>=12?5:oLv>=6?4:oLv>=3?3:2)+'</b> <button type="button" onclick="rage=Math.min(6,rage+1);paintActs();save()">+</button> <button type="button" class="'+(raging?'on':'')+'" onclick="raging=!raging;paintActs();save()">'+(raging?'Raging':'Not raging')+'</button></span></div>';h+='<div class="card"><div><b>Reckless Attack</b><p class="muted">Advantage on your melee attack.</p></div><button type="button" class="'+(reckless?'on':'')+'" onclick="reckless=!reckless;paintActs();save()">'+(reckless?'Advantage on':'Advantage off')+'</button></div>';}else{h+='<div class="card"><div><b>Second Wind</b><p class="muted">Bonus action. 1d10 + '+bLv+' HP.</p></div><span><button type="button" onclick="sw=Math.max(0,sw-1);paintActs();save()">-</button> <b>'+sw+'/1</b> <button type="button" onclick="sw=Math.min(1,sw+1);paintActs();save()">+</button></span></div>';h+='<div class="card"><div><b>Action Surge</b><p class="muted">Extra Action. Returns after a short rest.</p></div><span><button type="button" onclick="surge=Math.max(0,surge-1);paintActs();save()">-</button> <b>'+surge+'/'+(bLv>=17?2:1)+'</b> <button type="button" onclick="surge=Math.min(2,surge+1);paintActs();save()">+</button></span></div>';}root.innerHTML=h}
function paintChecks(){const root=$('checks');if(!root)return;root.innerHTML='';CHECKS.forEach(c=>{const m=mod(sc(c[0])),add=c[2]?pb():0,tot=m+add;const row=document.createElement('div');row.className='row';row.innerHTML='<span>'+c[1]+'<br><span class="muted">'+c[0]+' '+signed(m)+(c[2]?' + training from '+c[3]:' not trained')+'</span></span><b>'+signed(tot)+'</b>';row.onclick=()=>say(c[1]+': d20 + '+signed(tot)+'.');root.appendChild(row)})}
function paintPack(){if($('worn'))$('worn').innerHTML=HEADS[who].worn.map(x=>'<li>'+x+'</li>').join('');if($('bag'))$('bag').innerHTML=bag.length?bag.map((it,i)=>'<div class="card"><b>'+it.name+'</b> x'+it.qty+' <button type="button" onclick="qty('+i+',-1)">-</button> <button type="button" onclick="qty('+i+',1)">+</button></div>').join(''):'<p class="muted">Bag empty.</p>';if($('gp'))$('gp').textContent=goldN}
function addItem(){const n=($('newItem')&&$('newItem').value||'').trim();if(!n)return;const f=bag.find(x=>x.name.toLowerCase()===n.toLowerCase());if(f)f.qty++;else bag.push({name:n,qty:1});$('newItem').value='';paintPack();save()}
function qty(i,n){bag[i].qty=Math.max(0,bag[i].qty+n);if(!bag[i].qty)bag.splice(i,1);paintPack();save()}
function hp(n){const p=pool[who];if(n<0)p.hp=Math.max(0,p.hp+n);else p.hp=Math.min(p.max,p.hp+n);paintHUD();save()}
function temp(n){pool[who].temp=Math.max(0,pool[who].temp+n);paintHUD();save()}
function maxHp(n){const p=pool[who];p.max=Math.max(1,p.max+n);if(p.hp>p.max)p.hp=p.max;paintHUD();save()}
function gold(n){goldN=Math.max(0,goldN+n);paintPack();save()}
function shortRest(){if(!confirm('Short rest? Second Wind and Action Surge return. Rage does not.'))return;sw=1;surge=bLv>=17?2:1;raging=false;paintAll();save()}
function longRest(){if(!confirm('Long rest? Full HP. Features return.'))return;pool[who].hp=pool[who].max;pool[who].temp=0;if(who==='o')rage=oLv>=12?5:oLv>=6?4:oLv>=3?3:2;sw=1;surge=bLv>=17?2:1;paintAll();save()}
function paintAll(){who=LOCK;paintHUD();paintScores();paintActs();paintChecks();paintPack()}
load();who=LOCK;
if($('notes'))$('notes').value=notes;
if($('newItem'))$('newItem').addEventListener('keydown',e=>{if(e.key==='Enter')addItem()});
if($('notes'))$('notes').addEventListener('input',()=>{notes=$('notes').value;save()});
window.addEventListener('hashchange',function(){readHash();paintAll();});
paintAll();
