const WHY={Athletics:'Strength +3 and trained +2 from Barbarian.',Survival:'Wisdom and trained +2 from Barbarian.','Animal Handling':'Wisdom and trained +2 from Fighter.',Perception:'Wisdom and trained +2 from Fighter.',Medicine:'Wisdom and trained +2 from Hermit.',Religion:'Intelligence and trained +2 from Hermit.'};
const HEADS={o:{name:'OINKER',sub:'Half-giant Ettin Barbarian 2, Hermit',int:8,wis:10,cha:14,cls:'barb',hd:'2d12',fact:'Right head and right arm. Hay wig, sloppy berry stain, purple scale shell over the right eye. Soft wool body. Grins at everything.',gear:['Greatsword (right hand)','Battleaxe on harness','Hay wig','Purple shell over right eye','Leather harness','Shared hide loincloth / half-bra']},b:{name:'BOINKER',sub:'Half-giant Ettin Fighter 2, Hermit',int:12,wis:12,cha:10,cls:'fight',hd:'2d10',fact:'Left head and left arm. Black oily helmet over the left eye. Sparse hairs. Hungry and angry. Wants sheep for the hole.',gear:['Brick mace / rod (left hand)','Flail on harness','Black oily helmet over left eye','Leather harness','Shared hide loincloth']}};
const SKILLS=[['Athletics','str',true],['Acrobatics','dex',false],['Sleight of Hand','dex',false],['Stealth','dex',false],['Arcana','int',false],['History','int',false],['Investigation','int',false],['Nature','int',false],['Religion','int',true],['Animal Handling','wis',true],['Insight','wis',false],['Medicine','wis',true],['Perception','wis',true],['Survival','wis',true],['Deception','cha',false],['Intimidation','cha',false],['Performance','cha',false],['Persuasion','cha',false]];
const $=function(id){return document.getElementById(id)};
let who='o',gold=40,raging=false,reckless=false,rage=2,sw=1,surge=1,bag=[],oLv=2,bLv=2;
let pool={o:{hp:23,max:23,temp:0},b:{hp:20,max:20,temp:0}};
const skillOn={};SKILLS.forEach(function(s){skillOn[s[0]]=s[2]});
function cur(){return pool[who]}
function say(t){$('rollout').textContent=t}
function mod(s){return Math.floor((s-10)/2)}
function signed(n){return (n>=0?'+':'')+n}
function bodyMod(ab){if(ab==='str')return 3;if(ab==='dex')return 1;if(ab==='int')return mod(HEADS[who].int);if(ab==='wis')return mod(HEADS[who].wis);if(ab==='cha')return mod(HEADS[who].cha);return 0}
function tab(id){['combat','actions','skills','inventory','album'].forEach(function(x){$('p'+x).className=x===id?'':'hide';$('t'+x).className=x===id?'on':'';})}
function snap(){return {v:1,pool:pool,notes:$('notes').value,gold:gold,rage:rage,sw:sw,surge:surge,raging:raging,reckless:reckless,bag:bag,oLv:oLv,bLv:bLv,updated:Date.now()}}
function encodeSave(obj){return btoa(unescape(encodeURIComponent(JSON.stringify(obj)))).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'')}
function decodeSave(str){str=(str||'').replace(/-/g,'+').replace(/_/g,'/');while(str.length%4)str+='=';return JSON.parse(decodeURIComponent(escape(atob(str))))}
function applySave(s,src){if(!s||typeof s!=='object')return;if(s.pool){if(s.pool.o)Object.assign(pool.o,s.pool.o);if(s.pool.b)Object.assign(pool.b,s.pool.b)}if(s.notes!=null)$('notes').value=s.notes;if(s.gold!=null)gold=s.gold;if(s.bag)bag=s.bag;if(s.oLv)oLv=s.oLv;if(s.bLv)bLv=s.bLv;if(s.rage!=null)rage=s.rage;if(s.sw!=null)sw=s.sw;if(s.surge!=null)surge=s.surge;if(s.raging!=null)raging=s.raging;if(s.reckless!=null)reckless=s.reckless;HEADS.o.hd=oLv+'d12';HEADS.b.hd=bLv+'d10';HEADS.o.sub='Half-giant Ettin Barbarian '+oLv+', Hermit';HEADS.b.sub='Half-giant Ettin Fighter '+bLv+', Hermit';$('syncnote').textContent='Loaded from '+src+'.';}
function save(){var data=snap();try{localStorage.setItem('ettinLegal',JSON.stringify(data))}catch(e){}try{history.replaceState(null,'','#'+encodeSave(data))}catch(e){}}
function paintHP(){var p=cur();$('hplab').textContent=HEADS[who].name+' HP';$('hp').textContent=p.hp;$('hpmax').textContent=p.max;$('tempv').textContent=p.temp;$('maxv').textContent=p.max;$('hdbox').textContent=HEADS[who].hd}
function paintActs(){var h='<h3>Action \u00b7 Attack</h3>';if((who==='o'&&oLv>=5)||(who==='b'&&bLv>=5))h+='<p class="tag">Extra Attack: two swings on the Attack action.</p>';if(HEADS[who].cls==='barb'){h+='<div class="use"><div><b>Greatsword</b><div class="tag">Hit +5 = Str +3 + prof +2 \u00b7 Dmg 2d6+3</div></div><button type="button" class="act" onclick="showAtk(\'Greatsword\',\'2d6\')">How</button></div>';h+='<div class="use"><div><b>Battleaxe</b><div class="tag">Hit +5 = Str +3 + prof +2 \u00b7 Dmg 1d8+3</div></div><button type="button" class="act" onclick="showAtk(\'Battleaxe\',\'1d8\')">How</button></div>';h+='<h3>Bonus action</h3><div class="use"><div><b>Rage</b><div class="tag">Start rage. +2 melee damage while it lasts.</div></div><button type="button" class="act '+(raging?'danger':'')+'" onclick="doRage()">'+rage+'/2</button></div>';h+='<h3>Special</h3><div class="use"><div><b>Reckless Attack</b><div class="tag">This turn roll two d20s to hit. Enemies also roll two at you.</div></div><button type="button" class="act '+(reckless?'danger':'')+'" onclick="doReck()">'+(reckless?'ON':'off')+'</button></div>';}else{h+='<div class="use"><div><b>Brick mace</b><div class="tag">Hit +5 = Str +3 + prof +2 \u00b7 Dmg 1d12+3</div></div><button type="button" class="act" onclick="showAtk(\'Brick mace\',\'1d12\')">How</button></div>';h+='<div class="use"><div><b>Flail</b><div class="tag">Hit +5 = Str +3 + prof +2 \u00b7 Dmg 1d8+3</div></div><button type="button" class="act" onclick="showAtk(\'Flail\',\'1d8\')">How</button></div>';h+='<h3>Bonus action</h3><div class="use"><div><b>Second Wind</b><div class="tag">Heal 1d10+fighter level. Then short rest.</div></div><button type="button" class="act" onclick="doSW()">'+sw+'/1</button></div>';h+='<h3>Special</h3><div class="use"><div><b>Action Surge</b><div class="tag">One extra Action this turn. Then short rest.</div></div><button type="button" class="act" onclick="doSurge()">'+surge+'/1</button></div>';}$('acts').innerHTML=h;}
function showAtk(n,w){var extra=(raging&&HEADS[who].cls==='barb')?'\nIf Rage is on, add +2 more to damage.':'';say(n+' attack\n1. Say you Attack.\n2. Roll a d20.\n3. Add +5 (Strength +3 and proficiency +2).\n4. Tell the DM that total.\n5. If it hits, roll '+w+' and add +3 Strength.'+extra);}
function whyPerc(){var w=bodyMod('wis'),p=skillOn.Perception?2:0;say('Passive Perception '+(10+w+p)+'.\n10 + Wisdom '+signed(w)+(p?' + trained +2.':'')+'\nThe DM uses this when you are not searching.')}
function doRage(){if(!raging){if(rage<=0){say('No Rage left until a long rest.');return}rage-=1;raging=true;say('Rage on. After a melee hit, add +2 damage.')}else{raging=false;say('Rage off')}paintActs();save()}
function doReck(){reckless=!reckless;paintActs();save();say(reckless?'Reckless on. Roll two d20s to hit. Keep the higher.':'Reckless off')}
function doSW(){if(sw<=0){say('Second Wind already used. Short rest gives it back.');return}sw-=1;say('Second Wind. Roll 1d10 + fighter level ('+bLv+'). Then tap Healed.');paintActs();save()}
function doSurge(){if(surge<=0){say('Action Surge already used. Short rest gives it back.');return}surge-=1;say('Action Surge. Take one extra Action now.');paintActs();save()}
function shortRest(){if(!confirm('Short rest about one hour? Second Wind and Action Surge refill.'))return;sw=1;surge=1;raging=false;paintActs();say('Short rest done.');save()}
function longRest(){if(!confirm('Long rest? Both heads fill HP. Rage, Second Wind, Action Surge refill.'))return;pool.o.hp=pool.o.max;pool.o.temp=0;pool.b.hp=pool.b.max;pool.b.temp=0;rage=2;raging=false;reckless=false;sw=1;surge=1;paintHP();paintActs();say('Long rest done.');save()}
function nextText(cls,lv){var n=lv+1,hp=cls==='barb'?9:8,g='';if(cls==='barb'){if(n===3)g='Choose a Primal Path.';else if([4,8,12,16,19].indexOf(n)>=0)g='Ability Score Increase or a feat.';else if(n===5)g='Extra Attack and Fast Movement.';else g='See the barbarian table.';}else{if(n===3)g='Choose a Fighter Archetype.';else if([4,6,8,12,14,16,19].indexOf(n)>=0)g='Ability Score Increase or a feat.';else if(n===5)g='Extra Attack.';else g='See the fighter table.';}return 'Next is level '+n+'. About +'+hp+' HP. '+g}
function showNext(){var t=HEADS[who].name+' is level '+(who==='o'?oLv:bLv)+'. '+nextText(HEADS[who].cls,who==='o'?oLv:bLv);$('nextbox').textContent=t;say(t)}
function track(d,w){if(w==='o'){oLv=Math.max(1,Math.min(20,oLv+d));HEADS.o.hd=oLv+'d12';HEADS.o.sub='Half-giant Ettin Barbarian '+oLv+', Hermit';}else{bLv=Math.max(1,Math.min(20,bLv+d));HEADS.b.hd=bLv+'d10';HEADS.b.sub='Half-giant Ettin Fighter '+bLv+', Hermit';}$('olvl').textContent=oLv;$('blvl').textContent=bLv;if(w===who){$('csub').textContent=HEADS[w].sub;paintHP();paintActs()}save()}
function paintBag(){var h='';bag.forEach(function(it,i){h+='<div class="use"><div><b>'+it.name+'</b> x'+it.qty+'</div><span><button type="button" class="act" onclick="useItem('+i+')">Use</button> <button type="button" class="act" onclick="chgItem('+i+',-1)">-</button> <button type="button" class="act" onclick="chgItem('+i+',1)">+</button></span></div>'});if(!bag.length)h='<p class="tag">Bag empty.</p>';$('bag').innerHTML=h}
function addItem(){var n=($('newitem').value||'').trim();if(!n){say('Type a name first.');return}var f=null;bag.forEach(function(x){if(x.name.toLowerCase()===n.toLowerCase())f=x});if(f)f.qty+=1;else bag.push({name:n,qty:1});$('newitem').value='';paintBag();save();say('Added '+n)}
function chgItem(i,n){bag[i].qty=Math.max(0,bag[i].qty+n);if(bag[i].qty===0)bag.splice(i,1);paintBag();save()}
function useItem(i){var n=bag[i].name;bag[i].qty-=1;if(bag[i].qty<=0)bag.splice(i,1);paintBag();save();var m='Used 1 '+n+'. Tell the DM.';if(/potion|heal/i.test(n))m+=' Roll the potion dice, then tap Healed.';say(m)}
function showHead(w){who=w;var h=HEADS[w];$('btnO').className=w==='o'?'on':'';$('btnB').className=w==='b'?'on':'';$('cname').textContent=h.name;$('csub').textContent=h.sub;$('flavor').textContent=h.fact;$('abs').innerHTML='';[['STR',17,3,5,1,'+3 from 17 Strength. Save +5 because both classes train Strength (+2 proficiency).'],['DEX',13,1,1,0,'+1 from 13 Dexterity. Save +1. Not trained.'],['CON',15,2,4,1,'+2 from 15 Constitution. Save +4 because both classes train Constitution (+2 proficiency).'],['INT',h.int,mod(h.int),mod(h.int),0,h.name+' Intelligence '+h.int+'. Modifier '+signed(mod(h.int))+'. Save is the same.'],['WIS',h.wis,mod(h.wis),mod(h.wis),0,h.name+' Wisdom '+h.wis+'. Modifier '+signed(mod(h.wis))+'. Save is the same.'],['CHA',h.cha,mod(h.cha),mod(h.cha),0,h.name+' Charisma '+h.cha+'. Modifier '+signed(mod(h.cha))+'. Save is the same.']].forEach(function(a){var d=document.createElement('div');d.className='ab';d.title=a[5];d.onclick=function(){say(a[5]+' Roll d20 and add the save number.')};d.innerHTML='<div>'+a[0]+'</div><div class="mod">'+signed(a[2])+'</div><div class="sc">'+a[1]+'</div><div class="sv'+(a[4]?' p':'')+'">save '+signed(a[3])+'</div>';$('abs').appendChild(d)});$('gear').innerHTML=h.gear.map(function(x){return '<li>'+x+'</li>'}).join('');$('headfact').textContent=h.fact;$('olvl').textContent=oLv;$('blvl').textContent=bLv;paintHP();paintActs();renderSkills();paintInv();paintBag();try{localStorage.setItem('ettinWho',w)}catch(e){}save();}
function renderSkills(){var box=$('skills');box.innerHTML='';SKILLS.forEach(function(s){var ab=bodyMod(s[1]),tr=skillOn[s[0]],tot=ab+(tr?2:0);var src=s[0]+' '+signed(tot)+'. '+s[1].toUpperCase()+' '+signed(ab)+(tr?' + proficiency +2.':' not trained.')+(WHY[s[0]]?' '+WHY[s[0]]:'')+' Roll d20. Tell the DM your roll '+signed(tot)+'.';var row=document.createElement('div');row.className='sk';row.title=src;row.onclick=function(){say(src)};row.innerHTML='<span><span class="dot'+(tr?' on':'')+'"></span>'+s[0]+'<span class="why">'+(tr?(WHY[s[0]]||'Trained +2'):s[1].toUpperCase()+' only')+'</span></span><span>'+signed(tot)+'</span>';box.appendChild(row)});$('pperc').textContent=10+bodyMod('wis')+(skillOn.Perception?2:0);$('pins').textContent=10+bodyMod('wis')+(skillOn.Insight?2:0)}
function paintInv(){$('gold').textContent=gold}
function chgGold(n){gold=Math.max(0,gold+n);paintInv();save()}
function chgHP(n){var p=cur();if(n<0){var left=-n;if(p.temp>0){var u=Math.min(p.temp,left);p.temp-=u;left-=u}p.hp=Math.max(0,p.hp-left)}else p.hp=Math.min(p.max,p.hp+n);say(HEADS[who].name+' HP '+p.hp+'/'+p.max+' (this head only)');paintHP();save()}
function chgTemp(n){cur().temp=Math.max(0,cur().temp+n);paintHP();save()}
function chgMax(n){var p=cur();p.max=Math.max(1,p.max+n);if(p.hp>p.max)p.hp=p.max;paintHP();save()}
function fullHeal(){var p=cur();p.hp=p.max;p.temp=0;paintHP();save();say(HEADS[who].name+' HP full')}
function copyLink(){save();var url=location.origin+location.pathname+'#'+encodeSave(snap());if(navigator.clipboard&&navigator.clipboard.writeText){navigator.clipboard.writeText(url).then(function(){say('Table link copied. Send it. Your buddy opens that link and sees your HP and notes.')}).catch(function(){$('sharebox').value=url;tab('album');say('Copy blocked. Link is in Notes. Send that whole text.')})}else{$('sharebox').value=url;tab('album');say('Link is in Notes. Send that whole text.')}}
function copyCode(){var code=encodeSave(snap());$('sharebox').value=code;tab('album');if(navigator.clipboard&&navigator.clipboard.writeText){navigator.clipboard.writeText(code).then(function(){say('Table code copied. Buddy pastes it in Notes and taps Load pasted code.')}).catch(function(){say('Code is in the Notes box. Copy it.')})}else say('Code is in the Notes box. Copy it.')}
function loadCode(){var raw=($('sharebox').value||'').trim();if(!raw){say('Paste a table code or a full table link first.');return}try{if(raw.indexOf('#')>=0)raw=raw.split('#').pop();applySave(decodeSave(raw),'table code');showHead(who);save();say('Table loaded for both heads.')}catch(e){say('That code did not read. Copy it again.')}}
function load(){var fromHash=null,fromLocal=null,fromOld=null;try{if(location.hash&&location.hash.length>8)fromHash=decodeSave(location.hash.slice(1))}catch(e){}try{fromLocal=JSON.parse(localStorage.getItem('ettinLegal')||'null')}catch(e){}try{fromOld=JSON.parse(localStorage.getItem('ettinSplit')||'null')}catch(e){}if(fromHash)applySave(fromHash,'table link');else if(fromLocal)applySave(fromLocal,'this phone');else if(fromOld)applySave(fromOld,'old phone save');var start='o';try{start=localStorage.getItem('ettinWho')||'o'}catch(e){}showHead(start)}
$('notes').oninput=save;
$('newitem').onkeydown=function(e){if(e.key==='Enter')addItem()};
load();
