const NAME='Hmmmable Syrup';
const SCORES={str:8,dex:12,con:15,int:13,wis:16,cha:10};
const SKILLS=[['Strength','Athletics',0,''],['Dexterity','Acrobatics',0,''],['Dexterity','Sleight of Hand',0,''],['Dexterity','Stealth',0,''],['Intelligence','Arcana',1,'Druid'],['Intelligence','History',0,''],['Intelligence','Investigation',0,''],['Intelligence','Nature',1,'Farmer'],['Intelligence','Religion',0,''],['Wisdom','Animal Handling',1,'Farmer'],['Wisdom','Insight',1,'Druid'],['Wisdom','Medicine',0,''],['Wisdom','Perception',1,'Druid'],['Wisdom','Survival',0,''],['Charisma','Deception',0,''],['Charisma','Intimidation',0,''],['Charisma','Performance',0,''],['Charisma','Persuasion',0,'']];
const CIRCLES=[['Land','Extra spells from a land type. Good caster. Permanent.'],['Moon','Better Wild Shape. More beast combat. Permanent.'],['Stars','Starry form. Constellation buffs. Permanent.'],['Sea','Storm and swim. Water and lightning. Permanent.'],['Spores','Fungus temp HP and poison. Permanent.'],['Wildfire','A fire spirit friend. Fire spells. Permanent.'],['Shepherd','Spirit totems that buff allies. Permanent.'],['Dreams','Hearth and teleport to rest. Permanent.']];
const $=id=>document.getElementById(id);
let lvN=1,order='',circle='',goldN=99,notes='Mom asked dad what he wanted for pancakes, more importantly what to name the kid. Hmmmable Syrup. Grew up cook and farmer. Wants to be syrup. Happy, excited, likes pancakes a lot. Makes pancakes out of spiders.',bag=[{name:'Leather armor',qty:1},{name:'Shield',qty:1},{name:'Sickle',qty:1},{name:'Staff',qty:1},{name:'Explorer pack',qty:1},{name:'Herbalism kit',qty:1},{name:'Frying pan',qty:1},{name:'Imperiable paper',qty:1}];
let pool={hp:12,max:12,temp:0},ws=0,slot1=2,insp=0;
function mod(s){return Math.floor((s-10)/2)}
function signed(n){return(n>=0?'+':'')+n}
function pb(){return lvN>=17?6:lvN>=13?5:lvN>=9?4:lvN>=5?3:2}
function say(t){if($('say'))$('say').textContent=t||''}
function ac(){return 11+mod(SCORES.dex)+2}
function slots(){return lvN>=3?4:lvN>=2?3:2}
function wsMax(){return lvN>=17?4:lvN>=6?3:lvN>=2?2:0}
function hpBump(){return 5+mod(SCORES.con)+2}
function store(){return 'hmmmable_v1'}
function writeHash(){var h='#lv='+lvN+';o='+encodeURIComponent(order)+';c='+encodeURIComponent(circle)+';hp='+pool.hp+';max='+pool.max+';g='+goldN;if(location.hash!==h)history.replaceState(null,'',h);}
function readHash(){var raw=(location.hash||'').replace(/^#/,'');if(!raw)return;raw.split(';').forEach(function(part){var kv=part.split('=');if(kv.length<2)return;var k=kv[0],v=decodeURIComponent(kv[1]||'');if(k==='lv'){var n=parseInt(v,10);if(n>=1&&n<=20)lvN=n;}if(k==='o')order=v;if(k==='c')circle=v;if(k==='hp')pool.hp=parseInt(v,10)||pool.hp;if(k==='max')pool.max=parseInt(v,10)||pool.max;if(k==='g')goldN=parseInt(v,10)||goldN;});}
function save(){writeHash();try{localStorage.setItem(store(),JSON.stringify({lvN,order,circle,goldN,notes:$('notes')?$('notes').value:'',bag,pool,ws,slot1,insp}))}catch(e){}}
function load(){try{var s=JSON.parse(localStorage.getItem(store())||'null');if(s){if(s.lvN)lvN=s.lvN;if(s.order!=null)order=s.order;if(s.circle!=null)circle=s.circle;if(s.goldN!=null)goldN=s.goldN;if(s.notes!=null)notes=s.notes;if(s.bag)bag=s.bag;if(s.pool)Object.assign(pool,s.pool);if(s.ws!=null)ws=s.ws;if(s.slot1!=null)slot1=s.slot1;if(s.insp!=null)insp=s.insp;}}catch(e){}readHash();if(lvN<1)lvN=1;slot1=Math.min(slot1,slots());ws=Math.min(ws,wsMax());writeHash();}
function tab(id){['fight','scores','checks','pack','journal'].forEach(x=>{var p=$('p-'+x);if(p)p.className=x===id?'':'hide';['t-','b-'].forEach(pre=>{var b=$(pre+x);if(b)b.className=x===id?'on':''})})}
function explain(k){if(k==='ac')say('Armor Class '+ac()+'. Leather 11 + Dexterity '+signed(mod(SCORES.dex))+' + shield +2.');if(k==='init')say('Initiative '+signed(mod(SCORES.dex))+'. Roll d20 + Dexterity.');if(k==='speed')say('Speed 30 feet. Size Small.');if(k==='pp')say('Passive Perception '+(10+mod(SCORES.wis)+pb())+'. 10 + Wisdom + training.');}
function paintHUD(){$('name').textContent=NAME;$('line').textContent='Halfling Druid '+lvN+' \u00b7 Farmer \u00b7 2 ft maple-syrup bottle'+(order?' \u00b7 '+order:'')+(circle?' \u00b7 Circle of the '+circle:'');$('lv').textContent=lvN;$('hp').textContent=pool.hp;$('hpMax').textContent=pool.max;$('ac').textContent=ac();$('init').textContent=signed(mod(SCORES.dex));$('pp').textContent=10+mod(SCORES.wis)+pb();if($('temp'))$('temp').textContent=pool.temp;if($('maxLab'))$('maxLab').textContent=pool.max;if($('hdLine'))$('hdLine').textContent='Hit Dice '+lvN+'d8. Tough already in the HP number (+2 per level).';if($('gp'))$('gp').textContent=goldN;if($('notes'))$('notes').value=notes;}
function paintScores(){var blocks=[['STR',SCORES.str,0],['DEX',SCORES.dex,0],['CON',SCORES.con,0],['INT',SCORES.int,1],['WIS',SCORES.wis,1],['CHA',SCORES.cha,0]];function box(a){var m=mod(a[1]),sav=m+(a[2]?pb():0);var el=document.createElement('div');el.className='ab';el.innerHTML='<div>'+a[0]+'</div><div class="mod">'+signed(m)+'</div><div class="sub">score '+a[1]+'</div><div class="sub">save '+signed(sav)+'</div>';el.onclick=function(){say(a[0]+' score '+a[1]+' modifier '+signed(m)+(a[2]?'. Save trained +'+pb():'. Save not trained')+'.')};return el}['railAbs','phoneAbs'].forEach(function(id){var r=$(id);if(!r)return;r.innerHTML='';blocks.forEach(function(a){r.appendChild(box(a))})});}
function pickOrder(k){order=k;say(k+' locked. Copy the address bar if you want to send this sheet.');save();paintAll();}
function pickCircle(k){circle=k;say('Circle of the '+k+' locked. Copy the address bar if you want to send this sheet.');save();paintAll();}
function levelPanel(){var h='',atk=signed(mod(SCORES.wis)+pb()),dc=8+pb()+mod(SCORES.wis);function card(t,d,btn){h+='<div class="card"><div><b>'+t+'</b><p class="muted">'+d+'</p></div>'+(btn||'')+'</div>'}if(!order){card('Level 1 \u2014 Primal Order','Pick one. Permanent unless you tap Change.');h+='<div class="card"><div><b>Magician</b><p class="muted">Extra cantrip. Add Wisdom to Arcana and Nature.</p></div><button type="button" onclick="pickOrder(\'Magician\')">Choose Magician</button></div>';h+='<div class="card"><div><b>Warden</b><p class="muted">Martial weapons and medium armor.</p></div><button type="button" onclick="pickOrder(\'Warden\')">Choose Warden</button></div>';return h;}card('Primal Order: '+order,'Permanent.','<button type="button" onclick="order=\'\';save();paintAll()">Change</button>');if(lvN>=2){card('Wild Shape','Bonus action. Spider, lizard, wolf, or horse. Returns on a long rest.');h+='<div class="card"><div><b>Wild Shape uses</b></div><span><button type="button" onclick="ws=Math.max(0,ws-1);paintActs();save()">-</button> <b>'+ws+'/'+wsMax()+'</b> <button type="button" onclick="ws=Math.min(wsMax(),ws+1);paintActs();save()">+</button></span></div>';}if(lvN>=3&&!circle){card('Level 3 \u2014 pick a Circle','Permanent.');CIRCLES.forEach(function(row){h+='<div class="card"><div><b>Circle of the '+row[0]+'</b><p class="muted">'+row[1]+'</p></div><button type="button" onclick="pickCircle(\''+row[0]+'\')">Choose '+row[0]+'</button></div>'});}if(circle)card('Circle of the '+circle,'Permanent.','<button type="button" onclick="circle=\'\';save();paintAll()">Change</button>');if(lvN>=4)card('Druid 4','Ability Score Improvement or a feat.');if(lvN>=5)card('Druid 5','Wild Resurgence. Third-level slots.');if(lvN>=6&&circle)card('Druid 6','Circle of the '+circle+' feature.');if(lvN>=7)card('Druid 7','Elemental Fury. Pick with the DM.');if(lvN>=8)card('Druid 8','Ability Score Improvement or a feat.');if(lvN>=10&&circle)card('Druid 10','Circle of the '+circle+' feature.');if(lvN>=12)card('Druid 12','Ability Score Improvement or a feat.');if(lvN>=14&&circle)card('Druid 14','Circle of the '+circle+' feature.');if(lvN>=15)card('Druid 15','Improved Elemental Fury.');if(lvN>=16)card('Druid 16','Ability Score Improvement or a feat.');if(lvN>=18)card('Druid 18','Beast Spells.');if(lvN>=19)card('Druid 19','Epic Boon feat.');if(lvN>=20)card('Druid 20','Archdruid. Last official level.');card('Spell save DC '+dc,'8 + training '+pb()+' + Wisdom '+signed(mod(SCORES.wis))+'.');card('Spell attack '+atk,'d20 + training + Wisdom. Tell the DM the total.');h+='<div class="card"><div><b>Level 1 slots</b></div><span><button type="button" onclick="slot1=Math.max(0,slot1-1);paintActs();save()">-</button> <b>'+slot1+'/'+slots()+'</b> <button type="button" onclick="slot1=Math.min(slots(),slot1+1);paintActs();save()">+</button></span></div>';return h;}
function lvlChg(d){var before=lvN;lvN=Math.max(1,Math.min(20,lvN+d));if(lvN>before){var g=hpBump();pool.max+=g;pool.hp=Math.min(pool.max,pool.hp+g);slot1=slots();if(lvN===2)ws=wsMax();say('Hmmmable Syrup is level '+lvN+'. HP +'+g+'. Max '+pool.max+'.');}paintAll();save();}
function paintActs(){var root=$('acts');if(!root)return;var h=levelPanel();h+='<h3>Attack</h3>';h+='<div class="card"><div><b>Sickle</b><p class="muted">Roll d20. Add +3 as written. If it hits roll 1d4 slashing.</p></div></div>';h+='<div class="card"><div><b>Staff</b><p class="muted">Roll d20. Add +3 as written. If it hits roll 1d6 bludgeoning.</p></div></div>';h+='<div class="card"><div><b>Frying pan</b><p class="muted">Roll d20. Add -1 Strength. If it hits roll 1d4 bludgeoning.</p></div></div>';h+='<div class="card"><div><b>Thorn Whip</b><p class="muted">Cantrip. d20 + '+signed(mod(SCORES.wis)+pb())+'. Hit: 1d6 piercing and pull 10 feet.</p></div></div>';h+='<h3>Cast</h3>';h+='<div class="card"><div><b>Cantrips</b><p class="muted">Druidcraft, Thorn Whip, Mending, Message. No slot.</p></div></div>';h+='<div class="card"><div><b>Always ready</b><p class="muted">Speak with Animals from Druidic.</p></div></div>';h+='<div class="card"><div><b>Prepared 1st level</b><p class="muted">Animal Friendship, Purify Food and Drink, Entangle, Cure Wounds.</p></div></div>';root.innerHTML=h}
function paintChecks(){var root=$('checks');if(!root)return;root.innerHTML='';SKILLS.forEach(function(c){var m=mod(SCORES[{Strength:'str',Dexterity:'dex',Constitution:'con',Intelligence:'int',Wisdom:'wis',Charisma:'cha'}[c[0]]]),add=c[2]?pb():0,tot=m+add;if(order==='Magician'&&(c[1]==='Arcana'||c[1]==='Nature'))tot+=mod(SCORES.wis);var row=document.createElement('div');row.className='row';row.innerHTML='<span>'+c[1]+'<br><span class="muted">'+c[0]+' '+signed(m)+(c[2]?' + training from '+c[3]:' not trained')+'</span></span><b>'+signed(tot)+'</b>';row.onclick=function(){say(c[1]+': d20 + '+signed(tot)+'.')};root.appendChild(row)});}function paintPack(){if($('worn'))$('worn').innerHTML='<li>Maple syrup bottle costume</li><li>Leather armor and shield</li>';if($('bag'))$('bag').innerHTML=bag.map(function(it,i){return '<div class="card"><b>'+it.name+'</b> x'+it.qty+' <button type="button" onclick="qty('+i+',-1)">-</button> <button type="button" onclick="qty('+i+',1)">+</button></div>'}).join('');if($('gp'))$('gp').textContent=goldN}
function addItem(){var n=($('newItem')&&$('newItem').value||'').trim();if(!n)return;var f=bag.find(function(x){return x.name.toLowerCase()===n.toLowerCase()});if(f)f.qty++;else bag.push({name:n,qty:1});$('newItem').value='';paintPack();save()}
function qty(i,n){bag[i].qty=Math.max(0,bag[i].qty+n);if(!bag[i].qty)bag.splice(i,1);paintPack();save()}
function hp(n){if(n<0)pool.hp=Math.max(0,pool.hp+n);else pool.hp=Math.min(pool.max,pool.hp+n);paintHUD();save()}
function temp(n){pool.temp=Math.max(0,pool.temp+n);paintHUD();save()}
function maxHp(n){pool.max=Math.max(1,pool.max+n);if(pool.hp>pool.max)pool.hp=pool.max;paintHUD();save()}
function gold(n){goldN=Math.max(0,goldN+n);paintPack();save()}
function shortRest(){if(!confirm('Short rest?'))return;say('Short rest. Hit Dice: roll d8 + Constitution +2.');save()}
function longRest(){if(!confirm('Long rest? Full HP. Slots and Wild Shape return.'))return;pool.hp=pool.max;pool.temp=0;slot1=slots();ws=wsMax();paintAll();save()}
function paintAll(){paintHUD();paintScores();paintActs();paintChecks();paintPack()}
load();
if($('notes'))$('notes').value=notes;
if($('newItem'))$('newItem').addEventListener('keydown',function(e){if(e.key==='Enter')addItem()});
if($('notes'))$('notes').addEventListener('input',function(){notes=$('notes').value;save()});
window.addEventListener('hashchange',function(){readHash();paintAll()});
paintAll();
